service: shift-code

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: production
  deploymentBucket:
    name: lambda.mariouher.com
  environment:
    TOKEN: ${env:TOKEN}

functions:
  fetch:
    handler: handler.fetch
    name: ${self:service}-${self:provider.stage}
    description: ${file(package.json):description}
    events:
      - http:
          path: /
          method: GET
          cors: true
      - http:
          path: /ps
          method: GET
          cors: true
      - http:
          path: /xbox
          method: GET
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 8080
